import type { Metadata } from "next";
import { Mulish, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Header/NavBar";
import Footer from "@/components/Footer/Footer";

const mulish = Mulish({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const plus_jakarta_sans = Plus_Jakarta_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.variable} ${plus_jakarta_sans.variable} font-mulish`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
